ANIMEQUOTES = (
    "Udah jangan Sok iye bilang jorok atau gasuka, ntar lu ketagihan gimana?. 'Drs Prabu.spd'",
    "Memek itu bagaikan nyawa bagi para kontol.  'Drs Prabu.spd'",
    "Jangan anggap intim menjijikan karena itu Adalah jalan bagi kita, jika itu menjijikan menurut anda, berarti anda sudah Tidak normal. 'Drs Prabu.spd'",
    "Kontol Adalah suatu kehidupan bagi para memek. 'Drs Prabu.spd'",
    "Normal sih Kalo kita suka memek bagi para lelaki. 'Drs Prabu.spd'",
    "Kenapa pas hujan enak nya intim? Karena intim itu dapat menghangat kan Badan Untuk wanita maupun lelaki. 'Drs Prabu.spd'",
    "Lubang memek itu bagaikan pintu Lift, yg ditekan Untuk dibuka. 'Drs Prabu.spd'",
    "Sperma Adalah cairan yg baik bagi kesehatan wanita. 'Drs prabu.spd'",
    "Belah berlubang Dan ada cairan yg basah sedikit, itu namanya Memek. 'Drs Prabu.spd'",
    "Banyak orang yang bilang bahwa saya mesum, kenapa? Karena saya normal jika Tidak bisa intim Maka anda Tidak dapat menemukan jalan. 'Drs Prabu.spd'",
    "Saya sudah bilang intim itu jalan kehidupan bukan sesuatu yang jorok. 'Drs Prabu.spd'",
    "Bersyukur lah bagi yg masih bisa mesum, karena mesum itu normal. 'Drs Prabu.spd'",
    "Prabu pernah Berkata intim itu Adalah jalan bagi kita, kenapa? Karena intim sudah wajar dilakukan oleh kita. 'Drs Prabu.spd'",
    "Kakashi~Hal-hal yang aku suka dan hal-hal yang aku benci.... Aku tidak ingin mengatakan itu padamu. Impianku untuk masa depan... Tidak pernah benar-benar memikirkannya. Sedangkan untuk hobiku... Aku punya banyak hobi", 
    "Kebanyakan dari kita bisa berhubungan dengan Shikamaru... Jenius saat lahir, Malas karena pilihan", 
    "Yo momma sangat gemuk. Kakashi menggunakan Kamui padanya dan kehabisan Chakra", 
    "Gadis mana pun bisa menjadi glamor. Yang harus kamu lakukan hanyalah berdiri diam dan terlihat bodoh", 
    "Saat Anda menemukan keberanian untuk menyerahkan hidup Anda untuk seseorang ... akan menjadi saat Anda memahami cinta", 
    "Cinta, gairah, mengapa kita terjebak oleh perasaan yang menyusahkan seperti itu? Pikiran tidak pernah bisa meluruskan segalanya, dan Anda kehilangan kendali untuk mengetahui apa yang masuk akal. Jauh di lubuk hati itu semua sangat menjengkelkan",
    "Perasaan yang kalian miliki untuk satu sama lain tidak akan diketahui kecuali jika kalian menyuarakannya", 
    "Terkadang orang baik membuat pilihan yang buruk, itu tidak berarti mereka adalah orang jahat, itu berarti mereka manusia. -Sui Ishida", 
    "Daripada menjadi orang yang menyakiti orang lain, jadilah orang yang terluka. -Sui Ishida", 
    "Semua orang membuat belokan yang salah sesekali– Ash Ketchum", 
    "Jadikan mimpi indahmu menjadi kenyataan, itu akan menjadi kebenaranmu. Jika ada yang bisa, itu kamu.– N, Pokemon Black/White", 
    "Lebih penting menguasai kartu yang kamu pegang daripada mengeluh tentang kartu yang diberikan lawanmu.– Grimsley", 
    "Kita memang memiliki banyak kesamaan. Bumi yang sama, udara yang sama, langit yang sama. Mungkin jika kita mulai melihat apa yang sama, daripada melihat apa yang berbeda, yah, siapa tahu?– Meowth", 
    "Hari itu empat tahun yang lalu... Saat aku tidak dibutuhkan oleh siapapun. Saat tak ada yang peduli padaku. Saat aku menyerah untuk hidup dan hendak melompat dari atap gedung... FB menyelamatkanku dengan satu pesan. Aku tidak peduli apakah itu lelucon atau tidak. Saya hanya senang bahwa seseorang tahu ... bahwa saya masih hidup ... bahwa tidak apa-apa bagi saya untuk hidup.~Moeka Kiryuu", 
    "Dengar, bahkan jika kita adalah musuh di dunia sebelumnya, sekarang aku satu-satunya sekutumu. Bahkan jika seluruh dunia berbalik melawanmu, aku akan terus menjadi satu-satunya sekutumu.– Moeka Kiryuu", 
    "Ketika saya menyadari, saya sudah berada di atap sebuah bangunan ... saya menjadi membenci segalanya. Saya muak duduk di kamar saya sambil memegang lutut saya juga. Jika tidak ada yang akan memperhatikan atau peduli jika saya mati maka ... apa gunanya hidup?~Meoka Kiryuu", 
    "Mereka yang memiliki kebijaksanaanlah yang paling bodoh. Sejarah telah menunjukkan hal ini kepada kita. Bisa dibilang ini adalah peringatan terakhir dari Tuhan bagi mereka yang melawan.– Rintaro Okabe", 
    "Alam semesta memiliki awal, tetapi tidak ada akhir. — Infinity. Bintang juga memiliki awal mereka sendiri, tetapi kekuatan mereka sendiri menyebabkan kehancuran mereka. — Finite.– Rintaro Okabe",
    "Hidup seharusnya tidak berarti berlebihan. Ini yang terbaik.~Rintaro Okabe",
    "Ilmuwan gila macam apa yang khawatir tidak mendapatkan cukup sayuran?– Rintaro Okabe", 
    "Ada dua jenis kebohongan: Kebohongan yang menyakitkan, dan kebohongan yang tidak menyakiti.- Itaru Hashida", 
    "Ada dua hal yang selalu diinginkan kolektor. Yang pertama adalah barang yang sangat langka. Yang kedua adalah rekan kerja yang bisa dibanggakan koleksinya.- Kurapika", 
    "Orang-orang hanya menganggapku menarik karena mereka tidak tahu apakah aku serius atau tidak.- Killua Zoldyck", 
    "Jika kamu ingin mengenal seseorang, cari tahu apa yang membuat mereka marah.- Gon Freecss", 
    "Hanya butuh satu detik bagi harta untuk berubah menjadi sampah.- Hisoka Morow", 
    "Potensi evolusi manusia tidak terbatas. - Isaac Netero",
    "Memek Adalah suatu kenikmatan bagi para lelaki, terutama saya suka sekali! - Drs. Prabu.spd",
    "Ketika kontol dimasukan kedalam memek bahh, itu rasa nya enak banget! - Drs. Prabu.spd",
    "Anda harus menikmati jalan memutar kecil sepenuhnya. Karena di situlah Anda akan menemukan hal-hal yang lebih penting daripada yang Anda inginkan.- Ging Freecss", 
    "Kamu Ingin Menjaga Semua Orang Dari Kematian? Itu Naif. Ini Perang. Orang Mati-Monyet D. Luffy", "Keadilan Akan Menang, Katamu? Tapi Tentu Saja! Siapapun yang Memenangkan Perang Ini Menjadi Keadilan!-Donquixote Doflamingo", 
    "Mimpi Rakyat... Tidak Berakhir -Marshall 'Blackbeard' D. Teach", 
    "Hanya Aku Yang Bisa Menyebut Impianku Bodoh! -Roronoa Zoro", 
    "Kapan Anda Pikir Orang Meninggal? Ketika Mereka Ditembak Jantungnya Dengan Pistol? Tidak. Ketika Mereka Dirusak Oleh Penyakit yang Tidak Dapat Disembuhkan? Tidak. Ketika Mereka Minum Sup yang Terbuat Dari Jamur Beracun? Tidak. Saatnya... Mereka Dilupakan!-Dr.Hiriluk",
)
