ANIMEQUOTES = (
    "Biasanya Goku mengatakan sesuatu yang gila...",
    "Permisi, tapi apakah kamu orang aneh di keluargamu?– Ash Ketchum",
    "Dunia ini tidak sempurna. Tapi itu ada untuk kita, melakukan yang terbaik.... itulah yang membuatnya sangat indah.~ Roy Mustang (Full Metal Alchemist)",
    "Mengetahui kesedihan itu tidak menakutkan. Yang menakutkan adalah mengetahui bahwa kamu tidak bisa kembali ke kebahagiaan yang bisa kamu miliki.~ Matsumoto Rangiku (Bleach)",
    "Mereka yang berdiri di atas menentukan apa yang salah dan apa yang benar! Tempat ini adalah tempat netral! Keadilan akan menang, katamu? Tapi tentu saja! Siapa pun yang memenangkan perang ini menjadi keadilan!~ Don Quixote Doflamingo (One Piece)" ,
    "Ketakutan adalah kebebasan! Penaklukan adalah pembebasan! Kontradiksi adalah kebenaran! Itu adalah fakta dunia ini! Dan kalian semua akan menyerah pada mereka, dasar babi dalam pakaian manusia!~ Satsuki Kiryuuin (Kill la Kill)",
    "Aku adalah harapan alam semesta. Aku adalah jawaban untuk semua makhluk hidup yang menyerukan perdamaian. Aku pelindung orang yang tidak bersalah. Aku adalah cahaya dalam kegelapan. Aku adalah kebenaran. Sekutu untuk kebaikan! Mimpi buruk bagimu! ~ Son Goku (Dragon Ball Z)",
    "Agama, ideologi, sumber daya, tanah, dendam, cinta atau hanya karena ... Tidak peduli betapa menyedihkan alasannya, itu cukup untuk memulai perang. Perang tidak akan pernah berhenti ada ... alasan dapat dipikirkan setelah fakta ... Sifat manusia mengejar perselisihan. ~Paine (Naruto Shippuden)",
    "Orang yang tidak bisa membuang sesuatu yang penting, tidak akan pernah bisa berharap untuk mengubah apapun.~ Armin Arlert (Shingeki no Kyojin / Attack on Titan)",
    "Berpikir kamu tidak baik dan tidak berharga adalah hal terburuk yang dapat kamu lakukan~ Nobito (Doraemon)",
    "Jangan menyerah, tidak ada rasa malu jatuh! Rasa malu yang sebenarnya adalah tidak berdiri lagi!~ Shintaro Midorima (Kuroko No Basket)", 
    "Ukuran sebenarnya dari seorang shinobi bukanlah bagaimana dia hidup tetapi bagaimana dia mati. Bukan apa yang mereka lakukan dalam hidup tetapi apa yang mereka lakukan sebelum mati yang membuktikan nilai mereka.", 
    "Mengetahui bahwa kamu berbeda hanyalah permulaan. Jika kamu menerima perbedaan ini, kamu akan dapat melewatinya dan tumbuh lebih dekat.– Nona Kobayashi", 
    "Menyerah adalah apa yang membunuh orang.– Hellsing", 
    "Tidak peduli seberapa dalam malam, pada akhirnya selalu berubah menjadi siang. - One Piece", 
    "Sebuah mimpi kurang berharga daripada tidak sama sekali jika kamu tidak memiliki orang lain untuk dibagikan.~Dousan Saitou", 
    "Kamu hanya akan menyadari bahwa kamu benar-benar mencintai seseorang jika mereka sudah menyebabkan rasa sakit yang luar biasa. Musuhmu tidak akan pernah bisa menyakitimu seperti yang bisa dilakukan orang yang kamu cintai. Orang-orang yang dekat dengan hatimu yang dapat memberimu luka paling menusuk. Cinta adalah pedang bermata dua, itu bisa menyembuhkan luka lebih cepat atau bisa menenggelamkan pedang lebih dalam.– Kenshin Himura", 
    "Saya tidak membutuhkan Surga. Namun, jika saya harus pergi ke Surga maka tolong, Tuhan, jangan membagi Surga menjadi dua. Tolong jangan membagi robot dari manusia.– Chiisana Hoshi yo Yume", 
    "Apa yang tidak bisa kamu capai sendiri, menjadi bisa dilakukan saat kamu bersama orang lain.– Taichi Yaegashi",
    "Sama seperti game, tidak peduli seberapa baik Anda memiliki hal-hal yang berbaris dalam hidup Anda, selalu ada sesuatu untuk membuat Anda tetap waspada.– Junichirou Kagami", 
    "Lakukan persis seperti yang kamu suka. Itulah arti sebenarnya dari kesenangan. Kesenangan mengarah pada kegembiraan dan kegembiraan mengarah pada kebahagiaan.– Gilgames", 
    "Jika kamu tidak bisa melakukan sesuatu, maka jangan. Fokus pada apa yang bisa kamu lakukan.~Shiroe", 
    "Kamu bisa memanggilku sesukamu, tapi aku akan mengambil kuemu.-L (dari Death Note)", 
    "Dunia ini busuk. Yang busuk harus mati.― Tsugumi Ohba", 
    "Kakashi~Hal-hal yang aku suka dan hal-hal yang aku benci.... Aku tidak ingin mengatakan itu padamu. Impianku untuk masa depan... Tidak pernah benar-benar memikirkannya. Sedangkan untuk hobiku... Aku punya banyak hobi", 
    "Kebanyakan dari kita bisa berhubungan dengan Shikamaru... Jenius saat lahir, Malas karena pilihan", 
    "Yo momma sangat gemuk. Kakashi menggunakan Kamui padanya dan kehabisan Chakra", 
    "Gadis mana pun bisa menjadi glamor. Yang harus kamu lakukan hanyalah berdiri diam dan terlihat bodoh", 
    "Saat Anda menemukan keberanian untuk menyerahkan hidup Anda untuk seseorang ... akan menjadi saat Anda memahami cinta", 
    "Cinta, gairah, mengapa kita terjebak oleh perasaan yang menyusahkan seperti itu? Pikiran tidak pernah bisa meluruskan segalanya, dan Anda kehilangan kendali untuk mengetahui apa yang masuk akal. Jauh di lubuk hati itu semua sangat menjengkelkan",
    "Perasaan yang kalian miliki untuk satu sama lain tidak akan diketahui kecuali jika kalian menyuarakannya", 
    "Terkadang orang baik membuat pilihan yang buruk, itu tidak berarti mereka adalah orang jahat, itu berarti mereka manusia. -Sui Ishida", 
    "Daripada menjadi orang yang menyakiti orang lain, jadilah orang yang terluka. -Sui Ishida", 
    "Semua orang membuat belokan yang salah sesekali– Ash Ketchum", 
    "Jadikan mimpi indahmu menjadi kenyataan, itu akan menjadi kebenaranmu. Jika ada yang bisa, itu kamu.– N, Pokemon Black/White", 
    "Lebih penting menguasai kartu yang kamu pegang daripada mengeluh tentang kartu yang diberikan lawanmu.– Grimsley", 
    "Kita memang memiliki banyak kesamaan. Bumi yang sama, udara yang sama, langit yang sama. Mungkin jika kita mulai melihat apa yang sama, daripada melihat apa yang berbeda, yah, siapa tahu?– Meowth", 
    "Hari itu empat tahun yang lalu... Saat aku tidak dibutuhkan oleh siapapun. Saat tak ada yang peduli padaku. Saat aku menyerah untuk hidup dan hendak melompat dari atap gedung... FB menyelamatkanku dengan satu pesan. Aku tidak peduli apakah itu lelucon atau tidak. Saya hanya senang bahwa seseorang tahu ... bahwa saya masih hidup ... bahwa tidak apa-apa bagi saya untuk hidup.~Moeka Kiryuu", 
    "Dengar, bahkan jika kita adalah musuh di dunia sebelumnya, sekarang aku satu-satunya sekutumu. Bahkan jika seluruh dunia berbalik melawanmu, aku akan terus menjadi satu-satunya sekutumu.– Moeka Kiryuu", 
    "Ketika saya menyadari, saya sudah berada di atap sebuah bangunan ... saya menjadi membenci segalanya. Saya muak duduk di kamar saya sambil memegang lutut saya juga. Jika tidak ada yang akan memperhatikan atau peduli jika saya mati maka ... apa gunanya hidup?~Meoka Kiryuu", 
    "Mereka yang memiliki kebijaksanaanlah yang paling bodoh. Sejarah telah menunjukkan hal ini kepada kita. Bisa dibilang ini adalah peringatan terakhir dari Tuhan bagi mereka yang melawan.– Rintaro Okabe", 
    "Alam semesta memiliki awal, tetapi tidak ada akhir. — Infinity. Bintang juga memiliki awal mereka sendiri, tetapi kekuatan mereka sendiri menyebabkan kehancuran mereka. — Finite.– Rintaro Okabe",
    "Hidup seharusnya tidak berarti berlebihan. Ini yang terbaik.~Rintaro Okabe",
    "Ilmuwan gila macam apa yang khawatir tidak mendapatkan cukup sayuran?– Rintaro Okabe", 
    "Ada dua jenis kebohongan: Kebohongan yang menyakitkan, dan kebohongan yang tidak menyakiti.- Itaru Hashida", 
    "Ada dua hal yang selalu diinginkan kolektor. Yang pertama adalah barang yang sangat langka. Yang kedua adalah rekan kerja yang bisa dibanggakan koleksinya.- Kurapika", 
    "Orang-orang hanya menganggapku menarik karena mereka tidak tahu apakah aku serius atau tidak.- Killua Zoldyck", 
    "Jika kamu ingin mengenal seseorang, cari tahu apa yang membuat mereka marah.- Gon Freecss", 
    "Hanya butuh satu detik bagi harta untuk berubah menjadi sampah.- Hisoka Morow", 
    "Potensi evolusi manusia tidak terbatas. - Isaac Netero", 
    "Anda harus menikmati jalan memutar kecil sepenuhnya. Karena di situlah Anda akan menemukan hal-hal yang lebih penting daripada yang Anda inginkan.- Ging Freecss", 
    "Kamu Ingin Menjaga Semua Orang Dari Kematian? Itu Naif. Ini Perang. Orang Mati-Monyet D. Luffy", "Keadilan Akan Menang, Katamu? Tapi Tentu Saja! Siapapun yang Memenangkan Perang Ini Menjadi Keadilan!-Donquixote Doflamingo", 
    "Mimpi Rakyat... Tidak Berakhir -Marshall 'Blackbeard' D. Teach", 
    "Hanya Aku Yang Bisa Menyebut Impianku Bodoh! -Roronoa Zoro", 
    "Kapan Anda Pikir Orang Meninggal? Ketika Mereka Ditembak Jantungnya Dengan Pistol? Tidak. Ketika Mereka Dirusak Oleh Penyakit yang Tidak Dapat Disembuhkan? Tidak. Ketika Mereka Minum Sup yang Terbuat Dari Jamur Beracun? Tidak. Saatnya... Mereka Dilupakan!-Dr.Hiriluk",
)
